version: "3.3"

services:
  postgres:
    image: postgres:13
    container_name: Postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo
    container_name: MongoDB
    restart: unless-stopped
    ports:
      - 27017:27017

  # api:
  #   build: ./backend
  #   container_name: Backend
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_NAME: challenge_primeit
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: admin
  #   ports:
  #     - 3315:3315
  #   depends_on:
  #     - postgres

  products:
    build: ./microservices/product
    container_name: Products
    ports:
      - 9005:9005
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb/challenge_primeit

  # cart:
  #   build: ./microservices/cart
  #   container_name: Cart
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_NAME: challenge_primeit
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: admin
  #   ports:
  #     - 9006:9006
  #   depends_on:
  #     - postgres